@extends('index')
    @section('content')
        <table>
            <thead>
                <tr>
                    <th>id</th>
                    <th>nombre</th>
                </tr>    
            </thead>
            <tbody>
                @foreach($data as $register)
                    <tr>
                        <td>{{$register['id']}}</td>
                        <td>{{$register['name']}}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endsection